POST http://localhost:2000/api/encuestas/agregarEncuesta
Content-Type: application/json

{
    "genero": "Hombre",
    "edad": 10,
    "rtaAfectivo": 5,
    "rtaSuavidad": 4,
    "rtaHumedad": 3,
    "rtaEsponjosidad": 4,
    "rtaFragilidad": 2,
    "rtaGrasoso": 3,
    "rtaCrocante": 4,
    "rtaDureza": 1
}
